language: python

python:
  - "2.7"
  - "3.3"
  - "3.5"

# Travis can be used to build for both Linux and OS X
os:
  - linux

cache: pip

# Ensure we are running on 14.04 instead of 12.04 on the Ubuntu side
sudo: required
dist: trusty

before_install:
  # OS extra info
  - uname -a
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  # Check everything was correctly installed (linux python path from sudo env)
  - echo $PATH
  - sudo echo $PATH
  - sudo python --version
  - sudo python -c "import struct; print(struct.calcsize('P') * 8)"
  - sudo pip --version
  - pyinstaller --version

install:
  - pip install -r requirements.txt

# Run the test suit and build the executable with the time stamp in its file name
script:
  - pyinstaller package/pyinstaller.spec

notifications:
  email:
    on_success: change
    on_failure: change
